apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pet-adoption
spec:
  ingressClassName: nginx

  tls:
    - hosts:
        - petadoption.ferdeve.fit
      secretName: petadoption-tls

  rules:
    - host: petadoption.ferdeve.fit
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pet-adoption
                port:
                  number: 80