apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

patches:
  - path: replica-patch.yaml

images:
  - name: 740994137090.dkr.ecr.eu-west-3.amazonaws.com/enterprise-devops-platform/pet-adoption
    newTag: build-8